In [1]:
#Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
#Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([11,22,40,10])
print("1-D array: ")
print(ar1)

#Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print("2-D array: ")
print(ar2)

1-D array: 
[11 22 40 10]
2-D array: 
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [4]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
arr1= np.array([1,2,4])
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
#Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, ar2.size, type(ar2)

((2, 5), 2, dtype('int64'), 10, numpy.ndarray)

In [6]:
# Create an array of shape (5, 5) with only ones
ones=np.ones([5,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
#Create array of shape (3,3,5) with only zeros
ar4 = np.zeros((3,3,5))
ar4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[3, 3],
       [6, 5],
       [8, 4],
       [4, 4],
       [0, 1],
       [3, 4],
       [9, 3]])

In [9]:
#Create a random array of floats between 0 and 1 of shape (3,5)
np.random.random((3,5))

array([[0.94807391, 0.24459405, 0.2379602 , 0.261512  , 0.48012128],
       [0.72479099, 0.09668011, 0.00725949, 0.4482596 , 0.89030238],
       [0.70820524, 0.00852147, 0.69588671, 0.43937593, 0.03244355]])

In [10]:
# Create an array of normally distributed random numbers

Normal_Dis = np.random.normal(0.5,5,15)
Normal_Dis

array([ -9.4553597 ,   6.00825594,  -1.19659052,  -1.1844546 ,
         2.1405273 ,  -3.30429561,  -1.4034582 ,  -4.2601672 ,
         0.87278818,   6.789898  , -11.82539317,  -1.44912413,
         9.57973524,   4.79809597,   5.39321673])

In [11]:
#set the random seed to 42
#Create a random array of numbers between 0 and 10 of size (4,6)
np.random.seed(42)
np.random.randint(10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
# Copy the code from the cell above and run it again
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr = np.random.randint(10, size=(4,6))
random_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [14]:
# Find the 0'th index of the latest array you created
random_arr[0]

array([6, 3, 7, 4, 6, 9])

In [15]:
# Get the first 2 rows of latest array you created
random_arr[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[:2,:2]

array([[6, 3],
       [2, 6]])

In [17]:
#Create a random array of numbers between 0 & 10 and an array of ones both of size (3,5),save them both to variables
ran = np.random.randint(10,size = (3,5))
ones = np.ones((3,5))
ran,ones

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
#Add the two arrays together
ran+ones

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [19]:
#Create another array of ones of shape(5,3)
ones1 = np.ones((5,3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:

#Try add the array of ones and the other most recent array together
#you can anticipate an error
ran+ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
#Do the same operation you just did but this time with a transpose on one array
tra = ran+ones1.T
tra

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [22]:

#Take the latest array to the power of 2 using the python way
tra**2

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [24]:
#Do the same thing with numpy way
np.power(tra,2)

array([[ 81.,   1., 100.,   9.,  49.],
       [ 16.,  81.,   9.,  25.,   9.],
       [ 49.,  25.,  81.,  49.,   4.]])

In [25]:
#Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(tra),np.min(tra),np.max(tra),np.std(tra),np.var(tra)

(5.6, 1.0, 10.0, 2.8000000000000003, 7.840000000000002)

In [26]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
r1 = np.random.randint(10, size = (3,3))
r2 = np.random.randint(10, size = (3,2))
r1 , r2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]),
 array([[6, 7],
        [2, 0],
        [3, 1]]))

In [27]:

# Perform a dot product on the two newest arrays you created
np.dot(r1, r2)


array([[37, 22],
       [97, 72],
       [35, 31]])

In [28]:
#Create two arrays of random integers between 0 to 10 both of size (4,3)
b1 = np.random.randint(10,size=(4,3))
b2 = np.random.randint(10,size=(4,3))
b1,b2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]),
 array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [29]:
#Perform a hadamard product on the two newest arrays you created
b1*b2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [30]:
#Perform a dot product on the two newest arrays you ceated 
#Error anticipated
np.dot(b1,b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [31]:

#Take the latest two arrays,perform a transpose on one of them and then perform a dot product on them both
np.dot(b1.T,b2)

array([[145, 168, 155],
       [ 63,  84,  81],
       [157, 146, 121]])

In [33]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
a1 = np.random.randint(10, size = (3,5))
a2 = np.random.randint(10, size = (3,5))

In [34]:
# Compare the two arrays with '>', '<=' and '==' 
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [35]:
a2


array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [36]:
a1 > a2

array([[False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [ True, False, False, False, False]])

In [37]:
a1 <= a2

array([[ True, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [38]:
a1 == a2

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [40]:
# Sort one of the arrays you just created in ascending order
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [41]:
np.sort(a1)

array([[0, 6, 7, 8, 8],
       [0, 0, 2, 7, 7],
       [0, 2, 2, 4, 7]])

In [42]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([0, 1, 2])

In [43]:
# Find the index with the maximum value in one of the arrays you've created
arr1

array([1, 2, 4])

In [44]:
np.argmax(arr1)

2

In [46]:
#Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [49]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
arr1

array([1, 2, 4])